# Generated by Django 5.2.6 on 2025-09-25 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DebitEnergie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("debit", models.IntegerField()),
                ("energie", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Energie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("prix", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Fabrication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Utilisation_Matiere_Premiere", models.IntegerField()),
                ("machines", models.IntegerField()),
                ("ressources_humaines", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Local",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("Localisation", models.CharField(max_length=100)),
                ("surface", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Localisation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("Taxe", models.IntegerField()),
                ("prix_m2", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Machine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("prix_achat", models.IntegerField()),
                ("cout_maintenance", models.IntegerField()),
                ("operateurs", models.CharField(max_length=100)),
                ("debit", models.IntegerField()),
                ("surface", models.IntegerField()),
                ("debit_energie", models.IntegerField()),
                ("taux_utilisation", models.IntegerField()),
                ("local", models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="MatierePremiere",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("stock", models.IntegerField()),
                ("emprise", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Metier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("renumeration", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Produit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("prix_vente", models.IntegerField()),
                ("quantite", models.IntegerField()),
                ("emprise", models.IntegerField()),
                ("local", models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="RessourceHumaine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("metier", models.CharField(max_length=100)),
                ("quantite", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="ApprovisionnementMatierePremiere",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantite", models.IntegerField()),
                ("localisation", models.CharField(max_length=100)),
                ("prix_unitaire", models.IntegerField(max_length=100)),
                ("delai", models.IntegerField()),
                (
                    "matiere_premiere",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="high_level.matierepremiere",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UtilisationMatierePremiere",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantite", models.IntegerField()),
                ("fabrication", models.ManyToManyField(to="high_level.fabrication")),
                (
                    "matiere_premiere",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="high_level.matierepremiere",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
