# Generated by Django 5.2.6 on 2025-09-25 14:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("high_level", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="approvisionnementmatierepremiere",
            name="prix_unitaire",
            field=models.IntegerField(),
        ),
    ]
