# Generated by Django 5.2.6 on 2025-09-26 06:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("high_level", "0002_alter_approvisionnementmatierepremiere_prix_unitaire"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fabrication",
            old_name="Utilisation_Matiere_Premiere",
            new_name="utilisation_matiere_premiere",
        ),
        migrations.RenameField(
            model_name="local",
            old_name="Localisation",
            new_name="localisation",
        ),
    ]
