# Generated by Django 5.2.6 on 2025-09-26 06:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "high_level",
            "0003_rename_utilisation_matiere_premiere_fabrication_utilisation_matiere_premiere_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="fabrication",
            name="produit",
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
