# Generated by Django 5.2.6 on 2025-09-26 07:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("high_level", "0004_fabrication_produit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fabrication",
            name="produit",
            field=models.CharField(),
        ),
    ]
